import { useSession } from "next-auth/react";
import Head from "next/head";

import { Header } from "@/components/header";
import { Kanban } from "@/components/kanban";

export default function Home() {
  const { data: session, status } = useSession();

  const KanbanComponent = {
    loading: <>loading...</>,
    unauthenticated: <>please sign in first</>,
    authenticated: <Kanban session={session} />,
  }[status];

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="mt-32 flex flex-col items-center">
        {KanbanComponent}
      </main>
    </>
  );
}
